# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Julian Stamp
description: >- # this means to ignore newlines until "baseurl:"
  Personal website.
baseurl: "/home" # the subpath of the site
url: "https://jdstamp.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
#    - name: Blog

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: julian.d.stamp@gmail.com
      link: mailto:julian.d.stamp@gmail.com
  follow:
    - name: Twitter
      link: http://twitter.com/JulianStamp1
      username: "@JulianStamp1"
    - name: LinkedIn
      link: http://linkedin.com/in/julian-stamp-03a5a3179
    - name: GitHub
      link: http://github.com/jdstamp
    - name: ORCID
      link: https://orcid.org/0000-0003-3014-6249

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
